#!/bin/bash

# Copyright 2019 The OpenVPN+PiHole Image Authors All rights reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

pkg install ccrypt jq openssh wget
wget do.co/pihole-vpn-up -O vpn-up
wget do.co/pihole-vpn-down -O vpn-down
chmod +x vpn-up vpn-down
mv vpn-up vpn-down .shortcuts
echo -n "Enter your API key: "
read -s key
echo
echo "$key" > do-api
ccrypt do-api
