#!/bin/bash

# Copyright 2019 The OpenVPN+PiHole Image Authors All rights reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo "hiya! (ن╹◡╹)੭``"
if [ ! -f "do-api.cpt" ]
then
    echo "do-api.cpt not found"
    echo "  1. Create an api token (cloud.digitalocean.com/account/api/)"
    echo "  2. Save it in in the same directory as this script: do-api"
    echo "  3. Encrypt it with: ccrypt do-api"
    exit 1
fi

TAG='pihole-ovpn-1click'
TOKEN="$(ccrypt -c do-api.cpt)" || exit 1
TOKEN="$(echo "$TOKEN" | tr -d '\n')"

echo "Deleting droplets tagged with '$TAG'..."
DROPLETS="$(curl -s -X GET -H "Authorization: Bearer $TOKEN" \
    https://api.digitalocean.com/v2/droplets)"
COUNT=0
for i in $(echo "$DROPLETS" | jq ".droplets[] | \
           select(.tags | index(\"$TAG\")) | .id")
do
    echo -n "    Deleting $i..."
    curl -X DELETE -H "Authorization: Bearer $TOKEN" \
        "https://api.digitalocean.com/v2/droplets/$i"
    echo "Done"
    COUNT=$((COUNT+1))
done
echo "$COUNT droplets were deleted."

echo "ヾ(^_^) byebye!!"
echo "Press any key to exit..."
read
